# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='性别'),
        ),
    ]
